variables:
  NPM_PREFIX: BondageClub/

check:
  stage: build
  only:
    - merge_requests
  image: node:16
  script:
    - npm --prefix $NPM_PREFIX ci
    - npm --prefix $NPM_PREFIX run -s scripts:lint
    - npm --prefix $NPM_PREFIX run -s assets:typecheck -- --pretty
    - npm --prefix $NPM_PREFIX run -s assets:check
