interface AssetGroupDefinition {
	Asset: (AssetDefinition | string)[];
	Group: string;
	ParentGroup?: string;
	Category?: string;
	Default?: boolean;
	IsRestraint?: boolean;
	AllowNone?: boolean;
	AllowColorize?: boolean;
	AllowCustomize?: boolean;
	Random?: boolean;
	Color?: string[];
	ParentSize?: string;
	ParentColor?: string;
	Clothing?: boolean;
	Underwear?: boolean;
	BodyCosplay?: boolean;
	Activity?: string[];
	AllowActivityOn?: string[];
	Hide?: string[];
	Block?: string[];
	Zone?: [number, number, number, number][];
	SetPose?: string[];
	AllowPose?: string[];
	AllowExpression?: string[];
	Effect?: string[];
	MirrorGroup?: string;
	RemoveItemOnRemove?: { Group: string, Name: string, Type?: string }[];
	Priority?: number;
	Left?: number;
	Top?: number;
	FullAlpha?: boolean;
	Blink?: boolean;
	InheritColor?: string;
	FreezeActivePose?: string[];
	PreviewZone?: [number, number, number, number];
	DynamicGroupName?: string;
}

interface AssetDefinition {
	Name: string,
	ParentItem?: string;
	ParentGroup?: string | null;
	Enable?: boolean;
	Visible?: boolean;
	Wear?: boolean;
	Activity?: string | string[];
	AllowActivity?: string[];
	AllowActivityOn?: string[];
	BuyGroup?: string;
	PrerequisiteBuyGroups?: string[];
	Effect?: string[];
	Bonus?: string;
	Block?: string[];
	Expose?: string[];
	Hide?: string[];
	HideItem?: string[];
	HideItemExclude?: string[];
	Require?: string[];
	SetPose?: string[];
	AllowPose?: string[];
	HideForPose?: string[];
	AllowActivePose?: string[];
	WhitelistActivePose?: string[];
	Value?: number;
	Difficulty?: number;
	SelfBondage?: number;
	SelfUnlock?: boolean;
	ExclusiveUnlock?: boolean;
	Random?: boolean;
	RemoveAtLogin?: boolean;
	Time?: number;
	LayerVisibility?: boolean;
	RemoveTime?: number;
	RemoveTimer?: number;
	MaxTimer?: number;
	Priority?: number;
	Left?: number;
	Top?: number;
	Height?: number;
	Zoom?: number;
	Alpha?: { Group?: string[], Pose?: string[], Masks: [number, number, number, number][] }[];
	Prerequisite?: string | string[];
	Extended?: boolean;
	AlwaysExtend?: boolean;
	AlwaysInteract?: boolean;
	AllowLock?: boolean;
	IsLock?: boolean;
	PickDifficulty?: number | null;
	OwnerOnly?: boolean;
	LoverOnly?: boolean;
	ExpressionTrigger?: { Name: string, Group: string, Timer: number }[];
	RemoveItemOnRemove?: { Name: string, Group: string, Type?: string }[];
	AllowEffect?: string[];
	AllowBlock?: string[];
	AllowType?: string[];
	DefaultColor?: string | string[];
	Opacity?: number;
	MinOpacity?: number;
	MaxOpacity?: number;
	Audio?: string;
	Category?: string[];
	Fetish?: string[];
	ArousalZone?: string;
	IsRestraint?: boolean;
	BodyCosplay?: boolean;
	OverrideBlinking?: boolean;
	DialogSortOverride?: number;
	DynamicDescription?: (C: Character) => string;
	DynamicPreviewImage?: (C: Character) => string;
	DynamicAllowInventoryAdd?: (C: Character) => boolean;
	DynamicExpressionTrigger?: (C: Character) => ExpressionTrigger[] | null | undefined;
	DynamicName?: (C: Character) => string;
	DynamicGroupName?: string;
	DynamicActivity?: (C: Character) => string[] | string | null | undefined;
	DynamicAudio?: (C: Character) => string;
	CharacterRestricted?: boolean;
	AllowRemoveExclusive?: boolean;
	InheritColor?: string;
	DynamicBeforeDraw?: boolean;
	DynamicAfterDraw?: boolean;
	DynamicScriptDraw?: boolean;
	HasType?: boolean;
	AllowLockType?: string[];
	AllowColorizeAll?: boolean;
	AvailableLocations?: string[];
	OverrideHeight?: { Height: number; Priority: number; HeightRatioProportion?: number };
	FreezeActivePose?: string[];
	DrawLocks?: boolean;
	AllowExpression?: string[];
	MirrorExpression?: string;
	FixedPosition?: boolean;
	CustomBlindBackground?: any;
	Layer?: AssetLayerDefinition[];
	Archetype?: string;
	FuturisticRecolor?: boolean;
	FuturisticRecolorDisplay?: boolean;
	Attribute?: string[];
	HideItemAttribute?: string[];
	PreviewIcons?: string[];
}

interface AssetLayerDefinition {
	Name?: string;
	AllowColorize?: boolean;
	CopyLayerColor?: string;
	ColorGroup?: string;
	HideColoring?: boolean;
	AllowTypes?: string[];
	HasType?: boolean;
	Visibility?: string;
	ParentGroup?: string | null,
	AllowPose?: string[];
	Priority?: number;
	InheritColor?: string;
	Alpha?: { Group?: string[], Pose?: string[], Masks: [number, number, number, number][] }[],
	Left?: number;
	Top?: number;
	HideAs?: { Group: string, Asset: string };
	HasImage?: boolean;
	Opacity?: number;
	MinOpacity?: number;
	MaxOpacity?: number;
	LockLayer?: boolean;
	MirrorExpression?: string;
	HideForPose?: string[];
	AllowModuleTypes?: string[];
}
